@baseurl = http://127.0.0.1:8080/api

### GET all PROD checks
GET {{baseurl}}/checksPROD

### GET all NET checks
GET {{baseurl}}/checksNET

### GET all IT checks
GET {{baseurl}}/checksIT

### GET check by id
GET {{baseurl}}/checks/1?dep=it

### POST check
POST {{baseurl}}/checks
Content-Type: application/json

{

    "date": "",
    "state": "",
    "isChecked": false,
    "keyWords": []
}
### PUT

PUT {{baseurl}}/checks?dep=IT&id=1
Content-Type: application/json

{
  "date": "05.08.2024 14:30:00",
  "state": "updated state",
  "isChecked": true,
  "keyWords": [
    {
      "name": "updated keyword",
      "checkedBy": {
        "person": { "name": "John Doe" },
        "date": "2024-08-05T14:30:00Z",
        "department": "IT"
      }
    }
  ],
  "remark": "updated remark",
  "department": "IT",
  "id": 1
}

